-- Repair and standardize the order schema used by lib/ordering.ts.
-- Safe to run on an empty project or one with an existing orders table.

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null,
  "table" integer not null,
  user_id uuid references auth.users(id) on delete set null,
  notes text,
  total numeric(10, 2) not null,
  status text not null default 'sent' check (status in ('sent', 'preparing', 'ready', 'delivered')),
  created_at timestamptz not null default now()
);

-- Existing installations may have created orders before the app adopted this
-- schema. Add missing fields without replacing the table or losing data.
alter table public.orders add column if not exists order_number text;
alter table public.orders add column if not exists "table" integer;
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists notes text;
alter table public.orders add column if not exists total numeric(10, 2);
alter table public.orders add column if not exists status text default 'sent';
alter table public.orders add column if not exists created_at timestamptz default now();

-- Give any legacy rows a stable, visible order number.
update public.orders
set order_number = 'LEGACY-' || id::text
where order_number is null;

-- Replace the legacy status rule (which predates the staff order workflow)
-- with the values used by the application.
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders drop constraint if exists orders_status_check1;
alter table public.orders
  add constraint orders_status_check
  check (status in ('sent', 'preparing', 'ready', 'delivered'));
alter table public.orders alter column status set default 'sent';

-- Match order_items.order_id to the existing orders.id type. This supports
-- both a standard UUID primary key and older text-based order IDs.
do $$
declare
  order_id_type text;
begin
  select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
    into order_id_type
  from pg_catalog.pg_attribute attribute
  join pg_catalog.pg_class class on class.oid = attribute.attrelid
  join pg_catalog.pg_namespace namespace on namespace.oid = class.relnamespace
  where namespace.nspname = 'public'
    and class.relname = 'orders'
    and attribute.attname = 'id'
    and attribute.attnum > 0
    and not attribute.attisdropped;

  execute format(
    'create table if not exists public.order_items (
      id bigint generated by default as identity primary key,
      order_id %s not null references public.orders(id) on delete cascade,
      menu_item_id text not null,
      name text not null,
      price numeric(10, 2) not null,
      qty integer not null check (qty > 0)
    )',
    order_id_type
  );
end $$;

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

-- Customer devices may create an order, but only staff accounts can read the
-- complete order queue or change its status. The app marks staff users with
-- app_metadata.is_admin = true.
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Customers can create orders" on public.orders;
create policy "Customers can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff can view orders" on public.orders;
create policy "Staff can view orders"
on public.orders for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'is_admin') = 'true');

drop policy if exists "Staff can update orders" on public.orders;
create policy "Staff can update orders"
on public.orders for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'is_admin') = 'true')
with check ((auth.jwt() -> 'app_metadata' ->> 'is_admin') = 'true');

drop policy if exists "Customers can create order items" on public.order_items;
create policy "Customers can create order items"
on public.order_items for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff can view order items" on public.order_items;
create policy "Staff can view order items"
on public.order_items for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'is_admin') = 'true');

notify pgrst, 'reload schema';
